import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <a href="/final/default/123-123-123">Final default test page</a>
        <br></br>
        <a href="/final/ntrl/123-123-123">Final ntrl test page</a>
      </>
    </>
  );
}
